"use client";

/**
 * Client-side PDF generation (jspdf, loaded on demand). Produces a real .pdf
 * payment-record statement for an individual employee, with PF/ESI/TDS columns
 * shown only when they apply to that worker.
 */

import { COMPANY, PRODUCT } from "@/lib/company";
import type { HrEmployee } from "@/lib/hr-data";
import type { PaymentRecord } from "@/lib/payment-record";
import type { Settlement } from "@/lib/statutory";
import { categoryById } from "@/lib/hr-master";

function inr(n: number): string {
  return "Rs " + new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(n);
}

async function getJsPdf() {
  const mod = await import("jspdf");
  return mod.jsPDF ?? (mod as unknown as { default: typeof import("jspdf").jsPDF }).default;
}

/** Full payment record for one employee as a paginated PDF. */
export async function downloadPaymentRecordPdf(e: HrEmployee, rec: PaymentRecord) {
  const JsPDF = await getJsPdf();
  const pdf = new JsPDF({ unit: "pt", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  const H = pdf.internal.pageSize.getHeight();
  const M = 42;
  let y = 52;

  // Header
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(15);
  pdf.text(COMPANY.name, M, y);
  y += 15;
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(8.5); pdf.setTextColor(110);
  pdf.text(`${COMPANY.location} · ${COMPANY.industry} · Generated by ${PRODUCT.name}`, M, y);
  pdf.setTextColor(20);

  // Title band
  y += 24;
  pdf.setFillColor(5, 150, 105);
  pdf.rect(M, y - 14, W - M * 2, 24, "F");
  pdf.setTextColor(255); pdf.setFont("helvetica", "bold"); pdf.setFontSize(11);
  pdf.text("EMPLOYEE PAYMENT RECORD", M + 10, y + 2);
  pdf.setTextColor(20);

  // Employee meta
  y += 34;
  const cat = e.category === "MC_OTHERS" && e.categoryOther ? e.categoryOther : categoryById(e.category)?.label ?? e.category;
  const meta: [string, string][] = [
    ["Employee", `${e.name} (${e.id})`],
    ["Role / Dept", `${e.role} · ${e.department}${e.section ? " / " + e.section : ""}`],
    ["Category / Wage", `${cat} · ${e.wageType}${e.salaryPerDay ? ` (Rs ${e.salaryPerDay}/day)` : ""}`],
    ["Date of joining", e.doj],
    ["PF / ESI", rec.pfApplicable ? "Applicable" : "Not applicable"],
    ["TDS", rec.tdsApplicable ? "Applicable" : "Not applicable"],
  ];
  pdf.setFontSize(9);
  meta.forEach(([k, v]) => {
    pdf.setFont("helvetica", "bold"); pdf.text(k, M, y);
    pdf.setFont("helvetica", "normal"); pdf.text(String(v), M + 110, y);
    y += 15;
  });

  // Summary
  y += 6;
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(10);
  pdf.text(`Months paid: ${rec.monthsPaid}   ·   Total net paid: ${inr(rec.totalNet)}`, M, y);
  y += 8;

  // Table header
  const cols = rec.pfApplicable || rec.tdsApplicable
    ? [["Month", 90], ["Gross", 80], ["PF", 60], ["ESI", 55], ["TDS", 60], ["Deductions", 80], ["Net", 85]] as [string, number][]
    : [["Month", 130], ["Gross", 110], ["Deductions", 110], ["Net", 120]] as [string, number][];

  const drawHeader = () => {
    y += 18;
    pdf.setFillColor(238, 242, 240); pdf.rect(M, y - 12, W - M * 2, 18, "F");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(8.5); pdf.setTextColor(60);
    let x = M + 4;
    cols.forEach(([label, w], i) => { pdf.text(label, i === 0 ? x : x + w - 4, y, { align: i === 0 ? "left" : "right" }); x += w; });
    pdf.setTextColor(20); y += 6;
  };
  drawHeader();

  pdf.setFont("helvetica", "normal"); pdf.setFontSize(8.5);
  rec.rows.forEach((r) => {
    if (y > H - 60) { pdf.addPage(); y = 52; drawHeader(); pdf.setFont("helvetica", "normal"); pdf.setFontSize(8.5); }
    y += 15;
    const vals = rec.pfApplicable || rec.tdsApplicable
      ? [r.label, inr(r.gross), r.pf ? inr(r.pf) : "-", r.esi ? inr(r.esi) : "-", r.tds ? inr(r.tds) : "-", inr(r.deductions), inr(r.net)]
      : [r.label, inr(r.gross), inr(r.deductions), inr(r.net)];
    let x = M + 4;
    cols.forEach(([, w], i) => { pdf.text(String(vals[i]), i === 0 ? x : x + w - 4, y, { align: i === 0 ? "left" : "right" }); x += w; });
  });

  // Total row
  if (y > H - 60) { pdf.addPage(); y = 52; }
  y += 16;
  pdf.setDrawColor(200); pdf.line(M, y - 10, W - M, y - 10);
  pdf.setFont("helvetica", "bold");
  const totals = rec.pfApplicable || rec.tdsApplicable
    ? [`TOTAL (${rec.monthsPaid} mo)`, inr(rec.totalGross), inr(rec.totalPf), inr(rec.totalEsi), inr(rec.totalTds), inr(rec.totalDeductions), inr(rec.totalNet)]
    : [`TOTAL (${rec.monthsPaid} mo)`, inr(rec.totalGross), inr(rec.totalDeductions), inr(rec.totalNet)];
  let x = M + 4;
  cols.forEach(([, w], i) => { pdf.text(String(totals[i]), i === 0 ? x : x + w - 4, y, { align: i === 0 ? "left" : "right" }); x += w; });

  y += 30;
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(7.5); pdf.setTextColor(120);
  pdf.text("Computed statement — representative monthly figures. Verify against the payroll register before use.", M, y);

  pdf.save(`payment-record-${e.id}.pdf`);
}

/** Full & Final settlement statement for an exiting employee as a PDF. */
export async function downloadSettlementPdf(e: HrEmployee, s: Settlement) {
  const JsPDF = await getJsPdf();
  const pdf = new JsPDF({ unit: "pt", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  const M = 48;
  let y = 54;

  pdf.setFont("helvetica", "bold"); pdf.setFontSize(15);
  pdf.text(COMPANY.name, M, y);
  y += 15; pdf.setFont("helvetica", "normal"); pdf.setFontSize(8.5); pdf.setTextColor(110);
  pdf.text(`${COMPANY.location} · Generated by ${PRODUCT.name}`, M, y); pdf.setTextColor(20);

  y += 24; pdf.setFillColor(5, 150, 105); pdf.rect(M, y - 14, W - M * 2, 24, "F");
  pdf.setTextColor(255); pdf.setFont("helvetica", "bold"); pdf.setFontSize(11);
  pdf.text("FULL & FINAL SETTLEMENT", M + 10, y + 2); pdf.setTextColor(20);

  y += 34; pdf.setFontSize(9);
  const cat = e.category === "MC_OTHERS" && e.categoryOther ? e.categoryOther : categoryById(e.category)?.label ?? e.category;
  ([["Employee", `${e.name} (${e.id})`], ["Role / Category", `${e.role} · ${cat}`], ["Date of joining", e.doj], ["Status", e.status], ["Gratuity eligibility", `${s.gratuity.years} yrs — ${s.gratuity.eligible ? "eligible" : "not vested"}`]] as [string, string][]).forEach(([k, v]) => {
    pdf.setFont("helvetica", "bold"); pdf.text(k, M, y); pdf.setFont("helvetica", "normal"); pdf.text(String(v), M + 130, y); y += 15;
  });

  y += 8; pdf.setFont("helvetica", "bold"); pdf.setFontSize(9.5);
  pdf.text("Component", M, y); pdf.text("Credit", W - M - 150, y, { align: "right" }); pdf.text("Debit", W - M, y, { align: "right" });
  y += 4; pdf.setDrawColor(210); pdf.line(M, y, W - M, y);
  pdf.setFont("helvetica", "normal");
  s.lines.forEach((l) => {
    y += 16;
    pdf.text(l.label, M, y);
    if (l.kind === "credit") pdf.text("Rs " + l.amount.toLocaleString("en-IN"), W - M - 150, y, { align: "right" });
    else pdf.text("Rs " + l.amount.toLocaleString("en-IN"), W - M, y, { align: "right" });
  });
  y += 8; pdf.line(M, y, W - M, y);
  y += 16; pdf.setFont("helvetica", "bold");
  pdf.text("Totals", M, y);
  pdf.text("Rs " + s.totalCredits.toLocaleString("en-IN"), W - M - 150, y, { align: "right" });
  pdf.text("Rs " + s.totalDebits.toLocaleString("en-IN"), W - M, y, { align: "right" });

  y += 28; pdf.setFillColor(236, 253, 245); pdf.rect(M, y - 16, W - M * 2, 26, "F");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(11);
  pdf.text("NET SETTLEMENT PAYABLE", M + 10, y);
  pdf.text("Rs " + s.net.toLocaleString("en-IN"), W - M - 10, y, { align: "right" });

  y += 46; pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(120);
  pdf.text("Computed statement — verify gratuity, bonus and dues before disbursing. Employee & HR signatures required.", M, y);
  y += 34; pdf.setTextColor(20); pdf.setFontSize(9);
  pdf.text("_______________________", M, y); pdf.text("_______________________", W - M - 160, y);
  y += 14; pdf.setFontSize(8); pdf.setTextColor(110);
  pdf.text("Employee signature", M, y); pdf.text("Authorised signatory", W - M - 160, y);

  pdf.save(`settlement-${e.id}.pdf`);
}
